apiVersion: v1
kind: ConfigMap
metadata:
  name: ue-video
data:
  ue.yaml: |
    ues:
      - supi: "imsi-{{ .Values.mcc }}{{ .Values.mnc }}{{ .Values.initialMSISDN }}"
        mcc: "{{ .Values.mcc }}"
        mnc: "{{ .Values.mnc }}"
        key: "{{ .Values.key }}"
        op: "{{ .Values.op }}"
        opType: "{{ .Values.opType }}"
